### ISSUE TITLE
Choose the interface to use to find ip from providers

### ISSUE THREAD

**Issue by victornoel** [jasontbradshaw/gandi-dyndns#10]
I am using a VPN and it sets up the default route, so when gandi-dyndns tries to find the public ip of the machine, it will get the vpn public ip.

I was wondering how I could force gandi-dyndns to go through another route for checking the public ip and I think that if I want to take advantage of the providers functionality (and not the command), then some changes need to be made on gandi-dyndns itself... Not sure how though, but I can submit a PR if you have an idea how to do that :)

**Comment by victornoel** [comment]
Maybe using something like this: http://stackoverflow.com/a/1150408

?

**Comment by jasontbradshaw** [comment]
I actually stopped using Gandi a while ago, but I'd be glad to merge any PR you'd like to submit!

Sadly, I can't provide any guidance on how to do what you're asking since I've never encountered that particular situation.
