### ISSUE TITLE
Getting 403 from www.moanmyip.com

### ISSUE THREAD

**Issue by victornoel** [jasontbradshaw/gandi-dyndns#11]
Hi,

Lately I have been getting the following error when running this script:

```
[WARNING] Error getting external IP address from http://www.moanmyip.com/: HTTP Error 403: Forbidden
```

Could be that it does not work anymore and should be removed from the providers list?

**Comment by jasontbradshaw** [comment]
It could indeed mean just that. Feel free to submit a PR removing it!
