### ISSUE TITLE
TypeError: cannot marshal None unless allow_none is enabled

### ISSUE THREAD

**Issue by rgouveia-github** [jasontbradshaw/gandi-dyndns#18]
Hi there,
Thanks for creating this!
I was trying to use this with my domain (using the new gandi v5)  and I get this error: TypeError: cannot marshal None unless allow_none is enabled.
Any idea ? :-)

Cheers

Full debug (IP redacted):
```
$ LOG_LEVEL=DEBUG ./gandi_dyndns.py
2017-08-12 22:07:10,457 [DEBUG] Loading config file...
2017-08-12 22:07:10,457 [DEBUG] Config file loaded.
2017-08-12 22:07:10,459 [DEBUG] Getting external IP...
2017-08-12 22:07:10,993 [DEBUG] Got IP from provider http://ipinfo.io/ip: 92.xxx.xxx.xxx
2017-08-12 22:07:11,137 [DEBUG] Got IP from provider http://ip-api.com/csv: 92.xxx.xxx.xxx
2017-08-12 22:07:11,465 [DEBUG] Got IP from provider http://ventrilo.com/myip.php: 92.xxx.xxx.xxx
2017-08-12 22:07:11,465 [DEBUG] External IP is: 92.xxx.xxx.xxx
2017-08-12 22:07:11,466 [DEBUG] Getting domain info for domain 'cosmico.net'...
2017-08-12 22:07:11,969 [DEBUG] Got domain info.
2017-08-12 22:07:11,969 [DEBUG] Getting zone records for live zone version...
Traceback (most recent call last):
  File "./gandi_dyndns.py", line 357, in <module>
    main(sys.argv)
  File "./gandi_dyndns.py", line 353, in main
    update_ip()
  File "./gandi_dyndns.py", line 248, in update_ip
    zone_records = gandi.domain.zone.record.list(zone_id, 0)
  File "./gandi_dyndns.py", line 69, in __call__
    return getattr(self.proxy, method)(*key_args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1585, in __request
    allow_none=self.__allow_none)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1086, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 633, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 655, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 659, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
```

**Comment by cavebeat** [comment]
i have the same issue on v5

**Comment by cavebeat** [comment]
Found the problem in the debugger in https://github.com/jasontbradshaw/gandi-dyndns/blob/master/gandi_dyndns.py#L243
there is no return of any zone_id

The zone_id which is supplied to gandi.domain.zone.record.list(zone_id, 0) is empty in https://github.com/jasontbradshaw/gandi-dyndns/blob/master/gandi_dyndns.py#L248

the v4-API does use the v4 DNS System from Gandi. in v5 there is no zone-ID available. 

v4-DNS System is replaced with LiveDNS (without int zone_ID's)

> LiveDNS is Gandi's upcoming DNS platform, a completely new service that offers its own API and its own nameservers.

The good news: http://doc.livedns.gandi.net/#api-endpoint the new API can be used completely with CURL and BASH.

**Comment by cavebeat** [comment]
The Whole python script here is more or less replaced with: 
curl -X PUT -H "Content-Type: application/json" -H 'X-Api-Key: MY_SECRET_API_KEY' -d '{"items": [{"rrset_name": "SUBDOMAIN1", "rrset_type": "A", "rrset_ttl": 300, "rrset_values": ["127.0.0.1"]}, {"rrset_name": "SUBDOMAIN2", "rrset_type": "A", "rrset_ttl": 300, "rrset_values": ["127.0.0.1"]}]}' https://dns.beta.gandi.net/api/v5/zones/MY_NEW_UUID/records

FROM: http://doc.livedns.gandi.net/#managing-records
> Change all zone UUID records (application/json)
> 
>     PUT /zones/<UUID>/records:
> 
>     curl -X PUT -H "Content-Type: application/json" \
>                 -H 'X-Api-Key: XXX' \
>                 -d '{"items": [{"rrset_name": "<NAME1>",
>                                 "rrset_type": "<TYPE1>",
>                                 "rrset_ttl": 10800,
>                                 "rrset_values": ["<VALUE1>"]},
>                                {"rrset_name": "<NAME2>",
>                                 "rrset_type": "<TYPE2>",
>                                 "rrset_ttl": 10800,
>                                 "rrset_values": ["<VALUE2>"]}]}' \
>                 https://dns.beta.gandi.net/api/v5/zones/<UUID>/records

u need to find out your UUID first with: http://doc.livedns.gandi.net/#managing-zones

> List
> 
>     GET /zones:
> 
>     curl -H 'X-Api-Key: XXX' https://dns.beta.gandi.net/api/v5/zones

**Comment by rgouveia-github** [comment]
Thank you @cavebeat , that's very useful :+1: 
Hopefully @jasontbradshaw will fix this soon.

**Comment by cavebeat** [comment]
i've started already, 
not polished yet, but in a working state already. 
https://github.com/cavebeat/gandi_live_dns/

some features like force update and command line arguments are coming soon.

**Comment by jasontbradshaw** [comment]
It seems that the time for this project has come to a close, sad as that may be. I don't have any real interest in maintaining this project anymore since I no longer use Gandi as a registrar for domains I want dynamic DNS on, and with their recent API change basically invalidating the entire purpose for this script, it seems prudent to "hand things off" to a project/person (like @cavebeat!) that will actively maintain it and give it the love it deserves.

I'll get around to updating the README soon and mark this project as deprecated, and hopefully link to some other projects that get the job done.
