### ISSUE TITLE
External IP from router/gateway

### ISSUE THREAD

**Issue by foudfou** [jasontbradshaw/gandi-dyndns#2]
It'd be nice to have the option to query our external IP from our router (http://192.168.0.1 for ex.). I think this our gateways are liable enough we don't have to rely on third-party services.

It looks like this is the same as having a single provider (ex: 192.168.0.1), so I've a (not so clean) patch ready on my [`gateway` branch](/foudfou/gandi-dyndns/tree/gateway).

**Comment by jasontbradshaw** [comment]
I think this use case has been solved by #6. If you disagree, please re-open and describe why that won't work.
