### ISSUE TITLE
Issue running as Cron Job

### ISSUE THREAD

**Issue by marxr88** [jasontbradshaw/gandi-dyndns#4]
I get no errors running it directly as:  ./gandi_dyndns.py
Running as a cron job I get the below:
```
2016-07-01 15:00:01,437 [DEBUG] Loading config file...
Traceback (most recent call last):
  File "/opt/gandiupdate/gandi_dyndns.py", line 326, in <module>
    main(sys.argv)
  File "/opt/gandiupdate/gandi_dyndns.py", line 322, in main
    update_ip()
  File "/opt/gandiupdate/gandi_dyndns.py", line 187, in update_ip
    config = load_config()
  File "/opt/gandiupdate/gandi_dyndns.py", line 141, in load_config
    with open('config.json') as f:
IOError: [Errno 2] No such file or directory: 'config.json'
```

The files are all stored in /opt/gandiupdate

**Comment by jasontbradshaw** [comment]
What OS are you running it on?

**Comment by marxr88** [comment]
CentOS 7 - Python 2.7.5

**Comment by jasontbradshaw** [comment]
It sounds like it's looking in the wrong directory for the `config.json` file. The script only looks in the "current" directory, which may be different than the one it resides in.

Make certain:
* There's a `config.json` file present in the directory the script resides in
* Cron is running the script from the same directory it resides in (i.e. `/opt/gandiupdate`)

You might need to use something like `cd /opt/gandiupdate && ./gandy_dyndns.py` as the script in your crontab for it to work. This would ensure that the script is being run from the same directory the config file is in.

**Comment by marxr88** [comment]
Just tried that and it's worked perfectly. Thanks for the script :)

The only thing I've changed is to delete any zone files over two versions old. 

Thanks!

**Comment by jasontbradshaw** [comment]
You're welcome!

**Comment by Adrien-Luxey** [comment]
I just had the same bug, it's unfortunate. I am surprised it used to work!
Your `cd` fix will do perfectly, anyhow.
And many thanks for this script :)
